In [51]:
import numpy as np

n = 10

np.sort(np.arange(n))[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
n = 5

mat_nums = np.diag(np.sort(np.arange(n))[::-1])
mat_sum = np.trace(mat_nums)

print('Матрица:\n', mat_nums)
print('Сумма диагональных элементов:', mat_sum)

Матрица:
 [[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Сумма диагональных элементов: 10


In [53]:
from numpy import linalg

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [54]:
import matplotlib.pyplot as plt

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
user_ids = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_lenght = np.linalg.norm(next_user_stats)
i = 0

for el in users_stats:
    user_lenght = np.linalg.norm(el)
    cos = np.dot(el, next_user_stats) / (user_lenght * next_user_lenght)
    if i == 0:
        max_cos = cos
        near_user = user_ids[i]
    elif max_cos < cos:
        max_cos = cos
        near_user = user_ids[i]
    i += 1
print('Самый похожий пользователь: user_id =', near_user)

Самый похожий пользователь: user_id = 8
